#!/bin/sh

yarn global remove browser-sync diff-so-fancy ember-cli eslint eslint-plugin-ember-suave jasmine-node tldr stylelint stylelint-config-standard babel-eslint typescript tslint
yarn global add browser-sync diff-so-fancy ember-cli eslint eslint-plugin-ember-suave jasmine-node tldr stylelint stylelint-config-standard babel-eslint typescript tslint
